# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.2.21"
androidGradlePlugin = "8.11.2"
kotlinPoet = "2.2.0"
coreKtx = "1.17.0"
kotlinxCoroutinesCore = "1.10.2"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.10.01"
junit = "6.0.0" # JUnit 版本
shadowJar = "8.1.1" # ShadowJar 插件版本
bytebuddy = "1.17.8" # ByteBuddy 版本
kavaRefCore = "1.0.2" # KavaRef 版本
kavaRefExt = "1.0.1" # KavaRef 版本

[libraries]
kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
bytebuddy = { group = "net.bytebuddy", name = "byte-buddy", version.ref = "bytebuddy" }
kavaRefCore = { module = "com.highcapable.kavaref:kavaref-core", version.ref = "kavaRefCore" }
kavaRefExt = { module = "com.highcapable.kavaref:kavaref-extension", version.ref = "kavaRefExt" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
composeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
composeMaterial3 = { group = "androidx.compose.material3", name = "material3" }
composeUi-toolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
composeUi-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }

[plugins]
shadowJar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowJar" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }