on:
  push:
    branches: [mamba]
  pull_request: {}
  release:
    types:
      - created

name: 原神？启动！

jobs:
  build:
    runs-on: ubuntu-latest
    name: 给 ${{ matrix.cross }} 安装原神
    strategy:
      matrix:
        cross:
          - linux-x64
          - linux-arm64
          - windows-shared-x86
          - windows-shared-x64
    steps:
      - uses: actions/checkout@v2
      - name: 为 ${{ matrix.cross }} 下载原神
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: 为 ${{ matrix.cross }} 安装原神
        run: |
          chmod +x gradlew
          chmod +x .scripts/build.sh
          chmod +x .scripts/setup_docker.sh
      - name: 为 ${{ matrix.cross }} 注册米哈游通行证
        run: ./gradlew build
      - name: Build native (${{ matrix.cross }})
        run: .scripts/setup_docker.sh
        env:
          CROSS: ${{ matrix.cross }}
      - name: 为 ${{ matrix.cross }} 打开原神
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.cross }}
          path: |
            native/cmake-build-release/bin

  build-jars:
    runs-on: ubuntu-latest
    name: 一键打开所有群友的原神
    steps:
      - uses: actions/checkout@v2
      - name: 打开群友们的原神
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: 给群友们登录米哈游通行证
        run: |
          chmod +x gradlew
      - name: 群友们点击进入原神
        run: ./gradlew clean
      - name: 群友们正在加载原神服务器配置
        run: >
          ./gradlew
          :launcher-old:packAll
          :launcher-old:copyApi
      - name: 群友们已经加载好了启动页动画
        uses: actions/upload-artifact@v2
        with:
          name: Jars
          path: |
            pack-release/build/libs


  upload-release-assets:
    runs-on: ubuntu-latest
    name: 最后的伟大启动
    needs: [ build-jars, build]
    steps:
      - uses: actions/checkout@v2
      - name: 启动页动画的大门已经加载好了
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: 按捺不住激动的心而一举点下
        run: |
          chmod +x gradlew
          mkdir temp
          mkdir temp/artifacts
      - uses: actions/download-artifact@v2
        with:
          path: temp/artifacts
      - name: 原神！启动！
        run: ./gradlew :ci-release-helper:uploadReleaseAssets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POST_URL: ${{ github.event.release.upload_url }}
